[build]
  base = "."  # Use the main folder (root) where index.html lives!
  command = ""  # No build needed â€“ skip npm junk
  publish = "."  # Serve files from the main folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  # This keeps your pretty URLs like /realestate working without .html
